import { useRef } from "react";
import Image from "next/image";
import Head from "next/head";
import { FiSearch } from "react-icons/fi";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const search_input = useRef();

  const handle_search = e => {
    e.preventDefault();
    const query = search_input.current.value;
    if (!query) return;
    router.push(`/search?query=${query}`)
  };
  return (
    <div>
      <Head>
        <title>Arad search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex justify-center items-center ">
        <div className="absolute top-6 right-14"></div>
        <div className="w-[30rem]">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            x="0"
            y="0"
            enableBackground="new 0 0 100 100"
            version="1.1"
            viewBox="0 0 100 100"
            xmlSpace="preserve"
            className="w-[10rem] mx-auto mb-8"
          >
            <path
              d="M61 44.6c0 5.9-5 10.8-11 10.8s-11-4.9-11-10.8v-5.4c0-5.9 5-10.8 11-10.8 3 0 5.8 1.2 7.8 3.2 2 1.9 3.3 4.6 3.3 7.6v5.4zm38.6-18.3c-.1-.3-.3-.6-.5-.9-1.4-2.8-3.1-5.4-5-7.8-.3-.4-.7-.9-1-1.3-2.1-2.6-5.4-4.1-8.7-4.1h-51c-6.1 0-11 4.9-11 10.8v32.4c0 5.9-5 10.8-11 10.8H5.5c-3 0-5.5 2.4-5.5 5.4 0 .8.2 1.5.4 2.1.1.3.3.6.5.9 1.4 2.8 3.1 5.4 5 7.8.3.4.7.9 1 1.3 2.1 2.6 5.4 4.1 8.7 4.1h17.8c6.1 0 11-4.9 11-10.8 0-3 2.5-5.4 5.5-5.4s5.5 2.4 5.5 5.4c0 3 1.2 5.7 3.3 7.6 2 2 4.7 3.2 7.8 3.2H72c6.1 0 11-4.9 11-10.8V44.6c0-5.9 5-10.8 11-10.8h.3c3 0 5.5-2.4 5.5-5.4.2-.8 0-1.5-.2-2.1z"
              fill="#38bdf8"
            ></path>
          </svg>
          <form
            className="relative flex items-center mx-5"
            onSubmit={e => handle_search(e)}
          >
            <input
              type="text"
              className="w-full dark:bg-gray-900 p-2 rounded-full transition-shadow focus:outline-none  focus:bg-transparent focus:shadow-sky-700 focus:shadow-md	hover:shadow-xl  duration-200  focus:text-gray-800 shadow-sm  pl-10 pr-[5rem] border border-[2px] border-sky-500 text-white"
              ref={search_input}
            />
            <button
              type="submit"
              className=" px-3 py-0.5 bg-sky-400 text-black font-semibold rounded-full absolute block  right-2 "
              onFocus={() => {}}
            >
              Search
            </button>
            <FiSearch className="text-sky-400 absolute group-focus:text-gray-500 left-3" />
          </form>
        </div>
      </div>
    </div>
  );
}
